language: ruby
rvm:
  - "1.9.3"
  # - jruby-19mode # JRuby in 1.9 mode
  # - rbx-18mode
  # - rbx-19mode

env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
before_script:
  - psql -c 'create database little_books_test' -U postgres