postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password:
  database: little_books_<%= Rails.env %>
  min_messages: ERROR

  defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "postgresql" %>
  #<<: *<%= "postgresql" %> #might need only this one. Not sure yet.


  development:
    <<: *defaults

  test:
    <<: *defaults

  staging:
    <<: *defaults

  production:
    <<: *defaults




#commenting these out to configure Travis CI
# development:
#   adapter: postgresql
#   encoding: UTF-8
#   database: little_books_development
#   pool: 5
#   host: localhost

# test:
#   adapter: postgresql
#   encoding: UTF-8
#   database: little_books_test
#   pool: 5
#   host: localhost


# production:
#   adapter: postgresql
#   encoding: UTF-8
#   database: little_books_production
#   pool: 5

