#commenting these out to configure Travis CI
development:
  adapter: postgresql
  # username: postgres
  # password:
  encoding: UTF-8
  database: little_books_<%= Rails.env %>
  pool: 5
  host: localhost

test:
  adapter: postgresql
  # username: postgres
  # password:
  encoding: UTF-8
  database: little_books_<%= Rails.env %>
  pool: 5
  host: localhost


production:
  adapter: postgresql
  # username: postgres
  # password:
  encoding: UTF-8
  database: little_books_<%= Rails.env %>
  pool: 5

# postgresql: &postgresql
#   adapter: postgresql
#   username: postgres
#   password:
#   database: little_books_<%= Rails.env %>
#   min_messages: ERROR

#   defaults: &defaults
#   pool: 5
#   timeout: 5000
#   host: localhost
#   <<: *<%= "postgresql" %>


#   development:
#     <<: *defaults

#   test:
#     <<: *defaults

#   staging:
#     <<: *defaults

#   production:
#     <<: *defaults
